### ISSUE TITLE
Not displaying option

### ISSUE THREAD

**Issue by thePeras** [NIAEFEUP/tts-fe#286]
"Mestrado em Estudos de Arte" -> "CMC - Conceitos de Museologia Contemporâ..."

Is you select the dropdown, no option is show, but using the random fill, it displays an option. For some reason, it is not showing in the dropdown

**Comment by tomaspalma** [comment]
I looked into it and this problem arises because that class (CMC) does not have any option with professors.

Because the professors array is empty, there is no professor id inside the `slot.professors` array which causes the dropdown not to display any option because it interprets it as if no professors were filtered.

![image](https://github.com/user-attachments/assets/47e45648-46cf-4ad0-94b2-bb503849ae25)

![image](https://github.com/user-attachments/assets/b70944b3-a510-4414-b3ca-6e9b01cf1ac9)

**Comment by thePeras** [comment]
Agree with the solution. Classes without teachers show always be displayed for cases like this.
