### ISSUE TITLE
In rare occasions classes can't be chosen

### ISSUE THREAD

**Issue by tomaspalma** [NIAEFEUP/tts-fe#314]
https://github.com/user-attachments/assets/4b170887-02c8-44e0-a464-d356ae90f500

**Comment by thePeras** [comment]
1. locks don't work when empty, but if you choose one option then remove it, now the lock can be toggled. (not a big thing, but not a consistent)
2. locked empty option, refresh page, now that option is infinity locked, and you can't toogle the lock due to 1.

So, solving 1 will both solving the 2, which is a more critical bug
